config/routes.rb
StockManagement::Application.routes.draw do

    resources :stocks

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  attr_accessible :item_name, :item_number, :item_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def index
    @stocks = Stock.all

  end


  def show
    @stock = Stock.find(params[:id])

  end


  def new
    @stock = Stock.new

  end


  def edit
    @stock = Stock.find(params[:id])
  end


  def create
    @stock = Stock.new(params[:stock])

    if @stock.save
      flash[:notice] = 'Stock was successfully created.'
      redirect_to @stock

    else
      flash[:alert] = 'Your post has not been saved'
      render  :new
    end
  end


  def update
    @stock = Stock.find(params[:id])


    if @stock.update_attributes(params[:stock])
      flash[:notice] = 'Stock was successfully updated.'
      redirect_to @stock

    else
      flash[:alert] = 'Error while updating'
      render :edit

    end
  end


  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy
    redirect_to @stock

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StockManagement</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stocks/_form.html.haml
= form_for(@stock) do |f|
  - if @stock.errors.any?
    #error_explanation
      %h2
        = pluralize(@stock.errors.count, "error")
        prohibited this stock from being saved:
      %ul
        - @stock.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :item_number
    %br/
    = f.number_field :item_number
  .field
    = f.label :item_name
    %br/
    = f.text_field :item_name
  .field
    = f.label :item_type
    %br/
    = f.text_field :item_type
  .actions
    = f.submit

app/views/stocks/edit.html.haml
%h1 Editing stock
= render 'form'
= link_to 'Show', @stock
|
\#{link_to 'Back', stocks_path}

app/views/stocks/index.html.haml
%h1 Listing stocks
%table
  %tr
    %th Item number
    %th Item name
    %th Item type
    %th
    %th
    %th
  - @stocks.each do |stock|
    %tr
      %td= stock.item_number
      %td= stock.item_name
      %td= stock.item_type
      %td= link_to 'Show', stock
      %td= link_to 'Edit', edit_stock_path(stock)
      %td= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Stock', new_stock_path

app/views/stocks/new.html.haml
%h1 New stock
= render 'form'
= link_to 'Back', stocks_path

app/views/stocks/show.html.haml
%p#notice= notice
%p
  %b Item number:
  = @stock.item_number
%p
  %b Item name:
  = @stock.item_name
%p
  %b Item type:
  = @stock.item_type
= link_to 'Edit', edit_stock_path(@stock)
|
\#{link_to 'Back', stocks_path}